export const webAppData = [
    {
        id: '1',
        title: "JavaScript Documentation using Vanilla JavaScript",
        thumbnail: "https://marquesfernandes.com/wp-content/uploads/2020/01/1555172.jpg",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "2",
        title: "Random Quote Machine using React JS",
        thumbnail: "./images/quote-machine.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "3",
        title: "Keeper App using React JS",
        thumbnail: "./images/keeper-app.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "4",
        title: "Former Porfolio Website Using Bootstrap",
        thumbnail: "./images/old-portfolio.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "5",
        title: "JavaScript Calculator Using React JS",
        thumbnail: "./images/javascript-calculator.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "6",
        title: "New Portfolio Website Using React JS",
        thumbnail: "./images/new-portfolio.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
]