export const webAppData = [
    {
        id: '1',
        title: "JavaScript Documentation",
        thumbnail: "https://marquesfernandes.com/wp-content/uploads/2020/01/1555172.jpg",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "2",
        title: "Random Quote Machine",
        thumbnail: "./images/quote-machine.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "3",
        title: "Keeper App",
        thumbnail: "./images/keeper-app.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "4",
        title: "Old Porfolio Website",
        thumbnail: "./images/old-portfolio.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "5",
        title: "JavaScript Calculator",
        thumbnail: "./images/javascript-calculator.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
    {
        id: "6",
        title: "New Portfolio Website",
        thumbnail: "./images/new-portfolio.png",
        vlogger: "Reymond R. Mesuga",
        topics: "Deep Learning",
        info: "Explains Neural Network very well",
    },
]